name: Real Estate Notifier

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every 10 minutes
  workflow_dispatch:         # Allows manual triggering

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug env
        run: |
          echo "EMAIL_USERNAME=$EMAIL_USERNAME"
          echo "RECEIVER_EMAILS=$RECEIVER_EMAILS"
          echo "EMAIL_PASSWORD=$EMAIL_PASSWORD"
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}          

      - name: Run script
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        run: |
          python sales_notification.py
